2024-02-18 23:02:58,964 - ERROR - HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6840093925:AAFiZp3EanwTTWIESteP6vuVbidF8iaGMgg/sendMessage?chat_id=5586674988&text=%3Cb%3E%D0%9D%D0%B0%D0%BF%D0%B8%D1%88%D0%B8+%D1%81%D0%B2%D0%BE%D0%B9+%D0%BF%D1%80%D0%BE%D0%BC%D1%82%3A%3C%2Fb%3E&reply_markup=%7B%22remove_keyboard%22%3A+true%7D&parse_mode=html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000020116F7EF10>, 'Connection to api.telegram.org timed out. (connect timeout=15)'))
